
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no
WS2812_DRIVER = vendor
MOUSEKEY_ENABLE = yes
ENCODER_ENABLE = yes
MCU = RP2040
BOOTLOADER = rp2040
VIAL_ENABLE = no
VIA_ENABLE = yes
RAW_ENABLE = yes
LTO_ENABLE = no
COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = no
DYNAMIC_KEYMAP_ENABLE = yes