#pragma once

#define ENCODER_BTN_PIN GP10

#define RGBLIGHT_LIMIT_VAL 160
#define RGBLIGHT_DEFAULT_HUE 128
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_VAL 96
#define RGBLIGHT_DEFAULT_SPD 128
#define ONBOARD_LED_PIN GP13

#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP0
#define I2C1_SCL_PIN GP1
#define I2C1_CLOCK_SPEED 100000
#define OLED_DISPLAY_128X64
#define OLED_IC OLED_IC_SH1106
#define OLED_COLUMN_OFFSET 2
#define OLED_DISPLAY_ADDRESS 0x3C
#define OLED_TIMEOUT 0
