MCU = RP2040
BOOTLOADER = rp2040
PLATFORM = rp2040
PYTHON = python
CONSOLE_ENABLE = yes
# No ChibiOS or TMK dependencies for RP2040
STRICT = no
EXTRAFLAGS += -Wno-error
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor

OLED_ENABLE = yes
I2C_DRIVER_REQUIRED = yes
OLED_DRIVER = sh1106
OLED_COLUMN_OFFSET = 2
OLED_TIMEOUT = 0
OLED_DISPLAY_ADDRESS = 0x3C
